apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "eero-q-ap4"
  description: "A cool quarkus app"
  annotations:
    argocd/app-name: eero-q-ap4-dev
    backstage.io/kubernetes-id: eero-q-ap4
    backstage.io/kubernetes-namespace: eero-q-ap4-dev
    janus-idp.io/tekton-enabled: 'true'
    janus-idp.io/tekton: eero-q-ap4-dev
    backstage.io/source-location: url:https://github.com/RedHatNordicsSA/eero-q-ap4
    backstage.io/techdocs-ref: url:https://github.com/RedHatNordicsSA/eero-q-ap4
    gitlab.com/project-slug: RedHatNordicsSA/eero-q-ap4
    quay.io/repository-slug: "/eero-q-ap4"
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.rh-ocp-01.cool.lab/#https://github.com/RedHatNordicsSA/eero-q-ap4?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.rh-ocp-01.cool.lab/#https://github.com/RedHatNordicsSA/eero-q-ap4?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "group:default/cool-lab"
  providesApis:
    - "eero-q-ap4"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "eero-q-ap4"
  description: "A cool quarkus app"
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/cool-lab"
  definition:
    $text: ./openapi.yaml
